#!/usr/bin/env bash
# Configures Nginx to add a custom X-Served-By header with the server hostname

# Install nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Insert header inside the main server block
sudo sed -i "/server_name _;/a add_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
