#!/usr/bin/env bash
# Bash script that installs and configures HAProxy load balancer

set -e

# Install prerequisites
sudo apt-get update -y
sudo apt-get install -y haproxy

# Enable HAProxy through init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy || echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg >/dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    daemon
    maxconn 4096

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout client  10s
    timeout connect 5s
    timeout server  10s

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 44.201.220.22:80 check
    server web-02 34.227.160.138:80 check
EOF

# Restart HAProxy
sudo service haproxy restart
echo "HAProxy installed and configured successfully."
